# Generated by Django 3.2.7 on 2021-09-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=32)),
                ('ram', models.CharField(max_length=20)),
                ('rom', models.IntegerField()),
                ('price', models.FloatField()),
                ('processor', models.CharField(max_length=32)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
